In [1]:
import numpy as np
import pandas as pd

## 第一题

In [2]:
data = {
    "姓名":["张三","李四","王五","赵六","钱七","孙八","周九"],
    "语文":[85,np.nan,78,92,np.nan,88,90],
    "数学":[76,88,np.nan,95,82,np.nan,85],
    "英语":[np.nan,93,80,87,91,79,83]
}
cols = ["语文","数学","英语"]

In [3]:
df = pd.DataFrame(data)
df

   姓名    语文    数学    英语
0  张三  85.0  76.0   NaN
1  李四   NaN  88.0  93.0
2  王五  78.0   NaN  80.0
3  赵六  92.0  95.0  87.0
4  钱七   NaN  82.0  91.0
5  孙八  88.0   NaN  79.0
6  周九  90.0  85.0  83.0

In [4]:
df.isna().sum()

姓名    0
语文    2
数学    2
英语    1
dtype: int64

In [5]:
round(df.isna().mean(),2)

姓名    0.00
语文    0.29
数学    0.29
英语    0.14
dtype: float64

In [6]:
df_drop = df.dropna()
df_drop

   姓名    语文    数学    英语
3  赵六  92.0  95.0  87.0
6  周九  90.0  85.0  83.0

In [7]:
df_mean = df.copy().fillna(df[cols].mean())
df_mean

   姓名    语文    数学    英语
0  张三  85.0  76.0  85.5
1  李四  86.6  88.0  93.0
2  王五  78.0  85.2  80.0
3  赵六  92.0  95.0  87.0
4  钱七  86.6  82.0  91.0
5  孙八  88.0  85.2  79.0
6  周九  90.0  85.0  83.0

In [8]:
df_median = df.copy().fillna(df[cols].median())
df_median

   姓名    语文    数学    英语
0  张三  85.0  76.0  85.0
1  李四  88.0  88.0  93.0
2  王五  78.0  85.0  80.0
3  赵六  92.0  95.0  87.0
4  钱七  88.0  82.0  91.0
5  孙八  88.0  85.0  79.0
6  周九  90.0  85.0  83.0

In [9]:
pd.DataFrame({
    "处理方式": ["原始数据", "删除缺失值", "均值填充", "中位数填充"],
    "语文平均分": [
        df["语文"].mean().round(2),
        df_drop["语文"].mean().round(2),
        df_mean["语文"].mean().round(2),
        df_median["语文"].mean().round(2)
    ]
})

    处理方式  语文平均分
0   原始数据   86.6
1  删除缺失值   91.0
2   均值填充   86.6
3  中位数填充   87.0

## 第二题

In [10]:
data = {
    "ID":[101,102,103,102,104,101,105,103],
    "姓名":["张三","李四","王五","李四","赵六","张三","钱七","王五"],
    "成绩":[85,92,78,92,88,85,90,78]
}

In [11]:
df = pd.DataFrame(data)
df

    ID  姓名  成绩
0  101  张三  85
1  102  李四  92
2  103  王五  78
3  102  李四  92
4  104  赵六  88
5  101  张三  85
6  105  钱七  90
7  103  王五  78

In [12]:
df.duplicated().sum()

3

In [13]:
df[df.duplicated(keep=False)]

    ID  姓名  成绩
0  101  张三  85
1  102  李四  92
2  103  王五  78
3  102  李四  92
5  101  张三  85
7  103  王五  78

In [14]:
df.drop_duplicates()

    ID  姓名  成绩
0  101  张三  85
1  102  李四  92
2  103  王五  78
4  104  赵六  88
6  105  钱七  90

In [15]:
df.drop_duplicates(subset='ID',keep='last')

    ID  姓名  成绩
3  102  李四  92
4  104  赵六  88
5  101  张三  85
6  105  钱七  90
7  103  王五  78

## 第三题

In [16]:
data = {
    "商品类别":["电子产品","服装","食品","电子产品","服装","食品","电子产品"],
    "商品名称":["手机","T恤","面包","电脑","牛仔裤","牛奶","平板"],
    "销量":[120,85,200,60,110,150,95],
    "单价":[3999,99,15,5999,199,6,2499]
}

In [17]:
df = pd.DataFrame(data)
df

   商品类别 商品名称   销量    单价
0  电子产品   手机  120  3999
1    服装   T恤   85    99
2    食品   面包  200    15
3  电子产品   电脑   60  5999
4    服装  牛仔裤  110   199
5    食品   牛奶  150     6
6  电子产品   平板   95  2499

In [18]:
df.sort_values('销量',ascending=False).head(3)

   商品类别 商品名称   销量    单价
2    食品   面包  200    15
5    食品   牛奶  150     6
0  电子产品   手机  120  3999

In [19]:
df.sort_values(['商品类别','销量'],ascending=[True,False])

   商品类别 商品名称   销量    单价
4    服装  牛仔裤  110   199
1    服装   T恤   85    99
0  电子产品   手机  120  3999
6  电子产品   平板   95  2499
3  电子产品   电脑   60  5999
2    食品   面包  200    15
5    食品   牛奶  150     6

In [20]:
df.sort_values('单价').reset_index(drop=True)

   商品类别 商品名称   销量    单价
0    食品   牛奶  150     6
1    食品   面包  200    15
2    服装   T恤   85    99
3    服装  牛仔裤  110   199
4  电子产品   平板   95  2499
5  电子产品   手机  120  3999
6  电子产品   电脑   60  5999

In [21]:
df.loc[df['商品类别']=='电子产品'].sort_values('销量',ascending=False).iloc[0]

商品类别    电子产品
商品名称      手机
销量       120
单价      3999
Name: 0, dtype: object

## 第四题

In [22]:
df['销售额'] = df['销量'] * df['单价']

In [23]:
df.groupby('商品类别').agg(
    总销量=('销量', 'sum'),
    平均单价=('单价', 'mean'),
    总销售额=('销售额', 'sum'),
    商品数=('商品名称', 'count')
).round(2).reset_index()

   商品类别  总销量     平均单价     总销售额  商品数
0    服装  195   149.00    30305    2
1  电子产品  275  4165.67  1077225    3
2    食品  350    10.50     3900    2

In [24]:
def a(df):
    return df.nlargest(1, '销售额')

In [25]:
df.groupby('商品类别').apply(a).reset_index(drop=True)

   商品类别 商品名称   销量    单价     销售额
0    服装  牛仔裤  110   199   21890
1  电子产品   手机  120  3999  479880
2    食品   面包  200    15    3000

In [26]:
x = df['销售额'].sum()
y = df.groupby('商品类别')['销售额'].sum().reset_index()
y['销售额占比'] = (y['销售额'] / x * 100).round(2).astype(str) + '%'
y

   商品类别      销售额   销售额占比
0    服装    30305   2.73%
1  电子产品  1077225  96.92%
2    食品     3900   0.35%

In [27]:
df[df['单价'] > 1000]

   商品类别 商品名称   销量    单价     销售额
0  电子产品   手机  120  3999  479880
3  电子产品   电脑   60  5999  359940
6  电子产品   平板   95  2499  237405

## 第五题

In [28]:
with pd.ExcelWriter("销售数据.xlsx", engine="openpyxl") as writer:
    df.to_excel(writer, index=False)
    writer.sheets["Sheet1"].column_dimensions["E"].number_format = "¥#,##0.00"

In [ ]:
pd.read_excel('销售数据.xlsx')

In [ ]:
df.to_csv("销售数据.csv", index=False, encoding='utf-8-sig')

In [32]:
q = df[df['销售额'] > 10000].reset_index(drop=True)
q.to_excel("文件名.xlsx", index=False, engine='openpyxl')

## 第六题

In [ ]:
data = {
    "客户ID":[1001,1002,1003,1002,1004,1005,1001,1006,np.nan,1007],
    "客户姓名":["张三","李四","王五","李四","赵六","钱七","张三","孙八","周九","吴十"],
    "消费日期":["2026-05-01","2026-05-02","2026-05-01","2026-05-02","2026-05-03",
              "2026-05-01","2026-05-04","2026-05-03",np.nan,"2026-05-05"],
    "消费金额":[289,560,1200,560,890,3500,450,720,980,15000],
    "支付方式":["微信","支付宝","微信","支付宝","银行卡","微信","支付宝",np.nan,"微信","支付宝"]
}

In [ ]:
df = pd.DataFrame(data)
df

In [ ]:
df = df.drop_duplicates()
df = df.dropna(subset=['客户ID','消费日期'])
df['支付方式'] = df['支付方式'].fillna(df['支付方式'].mode()[0])
df

In [ ]:
Q1 = df['消费金额'].quantile(0.25)
Q3 = df['消费金额'].quantile(0.75)
IQR = Q3 - Q1
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q1 + 1.5 * IQR

In [ ]:
df = df[(df['消费金额'] >= lower_bound) & (df['消费金额'] <= upper_bound)]
df

In [ ]:
df = df.copy()
df['消费日期'] = pd.to_datetime(df['消费日期'])
df['月份'] = df['消费日期'].dt.month
df['星期'] = df['消费日期'].dt.day_name()
df

In [ ]:
a = df.groupby('支付方式').agg(
    消费次数= ('消费金额', 'count'),
    总消费金额 = ('消费金额', 'sum'),
    平均消费金额 = ('消费金额', 'mean')
).round(2).reset_index()
a

In [ ]:
b = df.groupby(['客户ID','客户姓名'])['消费金额'].sum().reset_index().sort_values('消费金额',ascending=False).head(3).reset_index(drop=True)
b

In [ ]:
c = df.groupby('消费日期')['消费金额'].agg(
    每日总消费 = 'sum',
    每日消费次数 = 'count'
).reset_index()
c

In [ ]:
df.to_csv('清洗后消费数据.csv', index=False, encoding='utf-8-sig')
a.to_csv('支付方式统计.csv', index=False, encoding='utf-8-sig')
b.to_csv('消费前三客户.csv', index=False, encoding='utf-8-sig')
c.to_csv('每日消费统计.csv', index=False, encoding='utf-8-sig')

## 拓展