In [1]:
import pandas as pd

## 第一题

In [2]:
pd.Series(
    ['25°','27°','29°','30°','18°','25°','29°'],
    index=['星期一','星期二','星期三','星期四','星期五','星期六','星期日'],
    name='温度'
)

星期一    25°
星期二    27°
星期三    29°
星期四    30°
星期五    18°
星期六    25°
星期日    29°
Name: 温度, dtype: object

In [3]:
pd.Series(
    [69,59,85,75,45],
    index=['长孙纳','得到','德瑞','芙蓉','权威'],
    name='Python成绩'
)

长孙纳    69
得到     59
德瑞     85
芙蓉     75
权威     45
Name: Python成绩, dtype: int64

In [4]:
df = pd.DataFrame({
    '月份': ['1月','2月','3月'],
    '北京': [2.5, 5.1, 8.3],
    '上海': [50.2, 65.8, 80.1],
    '广州': [30.5, 55.2, 120.7]
})
df

   月份   北京    上海     广州
0  1月  2.5  50.2   30.5
1  2月  5.1  65.8   55.2
2  3月  8.3  80.1  120.7

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   月份      3 non-null      object
 1   北京      3 non-null      float64
 2   上海      3 non-null      float64
 3   广州      3 non-null      float64
dtypes: float64(3), object(1)
memory usage: 224.0+ bytes

In [6]:
df.describe()

             北京         上海          广州
count  3.000000   3.000000    3.000000
mean   5.300000  65.366667   68.800000
std    2.905168  14.954709   46.612552
min    2.500000  50.200000   30.500000
25%    3.800000  58.000000   42.850000
50%    5.100000  65.800000   55.200000
75%    6.700000  72.950000   87.950000
max    8.300000  80.100000  120.700000

## 第二题

In [7]:
data = {
    "姓名":["张三","李四","王五","赵六","钱七","孙八"],
    "性别":["男","男","女","男","女","女"],
    "年龄":[18,19,18,20,19,18],
    "Python成绩":[85,92,78,65,90,88],
    "SQL成绩":[76,88,95,82,80,93]
}
df = pd.DataFrame(data)

In [8]:
df.head(3)

   姓名 性别  年龄  Python成绩  SQL成绩
0  张三  男  18        85     76
1  李四  男  19        92     88
2  王五  女  18        78     95

In [9]:
df.tail(2)

   姓名 性别  年龄  Python成绩  SQL成绩
4  钱七  女  19        90     80
5  孙八  女  18        88     93

In [10]:
df.columns.tolist()

['姓名', '性别', '年龄', 'Python成绩', 'SQL成绩']

In [11]:
df.index.tolist()

[0, 1, 2, 3, 4, 5]

In [12]:
df[['Python成绩', 'SQL成绩']].agg(['mean','max','min']).round(2)

      Python成绩  SQL成绩
mean      83.0  85.67
max       92.0  95.00
min       65.0  76.00

In [13]:
df['性别'].value_counts()

性别
男    3
女    3
Name: count, dtype: int64

## 第三题

In [14]:
df.loc[df['性别'] == '女',:]

   姓名 性别  年龄  Python成绩  SQL成绩
2  王五  女  18        78     95
4  钱七  女  19        90     80
5  孙八  女  18        88     93

In [15]:
df.loc[df['Python成绩'] > 80,:]

   姓名 性别  年龄  Python成绩  SQL成绩
0  张三  男  18        85     76
1  李四  男  19        92     88
4  钱七  女  19        90     80
5  孙八  女  18        88     93

In [16]:
df.loc[(df['年龄'] == 18) & (df['SQL成绩'] > 80),:]

   姓名 性别  年龄  Python成绩  SQL成绩
2  王五  女  18        78     95
5  孙八  女  18        88     93

In [17]:
df.loc[:,['姓名','Python成绩','SQL成绩']]
# df.loc[:, (df.columns != '性别') & (df.columns != '年龄')]

   姓名  Python成绩  SQL成绩
0  张三        85     76
1  李四        92     88
2  王五        78     95
3  赵六        65     82
4  钱七        90     80
5  孙八        88     93

In [18]:
df.iloc[[1,3,5]]

   姓名 性别  年龄  Python成绩  SQL成绩
1  李四  男  19        92     88
3  赵六  男  20        65     82
5  孙八  女  18        88     93

## 第四题

In [19]:
score = ['Python成绩', 'SQL成绩']

In [20]:
df['平均分'] = df[score].mean(axis=1).round(2)
df['总分'] = df[score].sum(axis=1)
df

   姓名 性别  年龄  Python成绩  SQL成绩   平均分   总分
0  张三  男  18        85     76  80.5  161
1  李四  男  19        92     88  90.0  180
2  王五  女  18        78     95  86.5  173
3  赵六  男  20        65     82  73.5  147
4  钱七  女  19        90     80  85.0  170
5  孙八  女  18        88     93  90.5  181

In [21]:
df.loc[df['总分'] == df['总分'].max(),:]

   姓名 性别  年龄  Python成绩  SQL成绩   平均分   总分
5  孙八  女  18        88     93  90.5  181

In [22]:
df.loc[df['平均分'] >= 85,:].sort_values(by='平均分',ascending=False)

   姓名 性别  年龄  Python成绩  SQL成绩   平均分   总分
5  孙八  女  18        88     93  90.5  181
1  李四  男  19        92     88  90.0  180
2  王五  女  18        78     95  86.5  173
4  钱七  女  19        90     80  85.0  170

In [23]:
def rank(a):
    if a >= 90:
        return 'A'
    elif a >= 80:
        return 'B'
    else:
        return 'C'

In [24]:
df['python等级'] = df['Python成绩'].apply(rank)
df.loc[:,['姓名','Python成绩','python等级']].sort_values(by='python等级',ascending=False)

   姓名  Python成绩 python等级
2  王五        78        C
3  赵六        65        C
0  张三        85        B
5  孙八        88        B
1  李四        92        A
4  钱七        90        A

## 第五题

In [25]:
import numpy as np
dates = pd.date_range("2026-05-01","2026-05-10")
products = ["商品A","商品B","商品C","商品D"]
np.random.seed(42)

In [26]:
data = []
for date in dates:
    for product in products:
        sales = np.random.randint(1,1000)
        price = np.round(np.random.uniform(10,100),2)
        data.append([date,product,sales,price])

df = pd.DataFrame(data, columns=['日期','商品','销量','价格'])
df

           日期   商品   销量     价格
0  2026-05-01  商品A  103  81.69
1  2026-05-01  商品B  271  75.88
2  2026-05-01  商品C  701  63.72
3  2026-05-01  商品D  122  24.04
4  2026-05-02  商品A  331  51.33
5  2026-05-02  商品B  373  64.10
6  2026-05-02  商品C  664  68.58
7  2026-05-02  商品D  309  97.29
8  2026-05-03  商品A  492  94.47
9  2026-05-03  商品B  386  26.36
10 2026-05-03  商品C  277  65.57
11 2026-05-03  商品D  314  57.23
12 2026-05-04  商品A  748  12.08
13 2026-05-04  商品B  475  65.07
14 2026-05-04  商品C  682  14.20
15 2026-05-04  商品D  700  42.97
16 2026-05-05  商品A  190  18.15
17 2026-05-05  商品B  958  27.97
18 2026-05-05  商品C  567  98.49
19 2026-05-05  商品D  505  14.18
20 2026-05-06  商品A  819  71.23
21 2026-05-06  商品B  841  15.85
22 2026-05-06  商品C  388  94.80
23 2026-05-06  商品D   14  82.76
24 2026-05-07  商品A  777  11.44
25 2026-05-07  商品B  898  71.58
26 2026-05-07  商品C  367  71.49
27 2026-05-07  商品D  428  54.57
28 2026-05-08  商品A  943  25.60
29 2026-05-08  商品B   81  33.29
30 2026-05-08  商品C  872  77.98
31 2026-05-08  商品D  390  28.71
32 2026-05-09  商品A  772  26.64
33 2026-05-09  商品B  703  85.81
34 2026-05-09  商品C  556  94.55
35 2026-05-09  商品D  958  93.40
36 2026-05-10  商品A  863  92.97
37 2026-05-10  商品B  456  61.34
38 2026-05-10  商品C  252  14.07
39 2026-05-10  商品D  296  86.01

In [27]:
df.isna().sum()

日期    0
商品    0
销量    0
价格    0
dtype: int64

In [28]:
df['销售额'] = (df['销量'] * df['价格']).round(2)
df

           日期   商品   销量     价格       销售额
0  2026-05-01  商品A  103  81.69   8414.07
1  2026-05-01  商品B  271  75.88  20563.48
2  2026-05-01  商品C  701  63.72  44667.72
3  2026-05-01  商品D  122  24.04   2932.88
4  2026-05-02  商品A  331  51.33  16990.23
5  2026-05-02  商品B  373  64.10  23909.30
6  2026-05-02  商品C  664  68.58  45537.12
7  2026-05-02  商品D  309  97.29  30062.61
8  2026-05-03  商品A  492  94.47  46479.24
9  2026-05-03  商品B  386  26.36  10174.96
10 2026-05-03  商品C  277  65.57  18162.89
11 2026-05-03  商品D  314  57.23  17970.22
12 2026-05-04  商品A  748  12.08   9035.84
13 2026-05-04  商品B  475  65.07  30908.25
14 2026-05-04  商品C  682  14.20   9684.40
15 2026-05-04  商品D  700  42.97  30079.00
16 2026-05-05  商品A  190  18.15   3448.50
17 2026-05-05  商品B  958  27.97  26795.26
18 2026-05-05  商品C  567  98.49  55843.83
19 2026-05-05  商品D  505  14.18   7160.90
20 2026-05-06  商品A  819  71.23  58337.37
21 2026-05-06  商品B  841  15.85  13329.85
22 2026-05-06  商品C  388  94.80  36782.40
23 2026-05-06  商品D   14  82.76   1158.64
24 2026-05-07  商品A  777  11.44   8888.88
25 2026-05-07  商品B  898  71.58  64278.84
26 2026-05-07  商品C  367  71.49  26236.83
27 2026-05-07  商品D  428  54.57  23355.96
28 2026-05-08  商品A  943  25.60  24140.80
29 2026-05-08  商品B   81  33.29   2696.49
30 2026-05-08  商品C  872  77.98  67998.56
31 2026-05-08  商品D  390  28.71  11196.90
32 2026-05-09  商品A  772  26.64  20566.08
33 2026-05-09  商品B  703  85.81  60324.43
34 2026-05-09  商品C  556  94.55  52569.80
35 2026-05-09  商品D  958  93.40  89477.20
36 2026-05-10  商品A  863  92.97  80233.11
37 2026-05-10  商品B  456  61.34  27971.04
38 2026-05-10  商品C  252  14.07   3545.64
39 2026-05-10  商品D  296  86.01  25458.96

In [29]:
df.loc[df['销量'] == df['销量'].max(),:]

           日期   商品   销量     价格       销售额
17 2026-05-05  商品B  958  27.97  26795.26
35 2026-05-09  商品D  958  93.40  89477.20

In [30]:
dsales = df.groupby('日期')['销售额'].sum().reset_index()
days = dsales[dsales['销售额'] > 5000]['日期']
df.loc[df['日期'].isin(days), ['日期','销售额']]

           日期       销售额
0  2026-05-01   8414.07
1  2026-05-01  20563.48
2  2026-05-01  44667.72
3  2026-05-01   2932.88
4  2026-05-02  16990.23
5  2026-05-02  23909.30
6  2026-05-02  45537.12
7  2026-05-02  30062.61
8  2026-05-03  46479.24
9  2026-05-03  10174.96
10 2026-05-03  18162.89
11 2026-05-03  17970.22
12 2026-05-04   9035.84
13 2026-05-04  30908.25
14 2026-05-04   9684.40
15 2026-05-04  30079.00
16 2026-05-05   3448.50
17 2026-05-05  26795.26
18 2026-05-05  55843.83
19 2026-05-05   7160.90
20 2026-05-06  58337.37
21 2026-05-06  13329.85
22 2026-05-06  36782.40
23 2026-05-06   1158.64
24 2026-05-07   8888.88
25 2026-05-07  64278.84
26 2026-05-07  26236.83
27 2026-05-07  23355.96
28 2026-05-08  24140.80
29 2026-05-08   2696.49
30 2026-05-08  67998.56
31 2026-05-08  11196.90
32 2026-05-09  20566.08
33 2026-05-09  60324.43
34 2026-05-09  52569.80
35 2026-05-09  89477.20
36 2026-05-10  80233.11
37 2026-05-10  27971.04
38 2026-05-10   3545.64
39 2026-05-10  25458.96

In [31]:
df.groupby('商品').agg(
    总销量=('销量','sum'),
    平均销量=('销量','mean'),
    最高销量=('销量','max'),
    总销售额=('销售额','sum'),
    平均销售额=('销售额','mean')
).round(2)

      总销量   平均销量  最高销量       总销售额     平均销售额
商品
商品A  6038  603.8   943  276534.12  27653.41
商品B  5442  544.2   958  280951.90  28095.19
商品C  5326  532.6   872  361029.19  36102.92
商品D  4036  403.6   958  238853.27  23885.33

## 拓展

In [34]:
data = {
    "姓名":["张三","李四","王五","赵六","钱七","孙八"],
    "性别":["男","男","女","男","女","女"],
    "年龄":[18,19,18,20,19,18],
    "Python成绩":[85,92,78,65,90,88],
    "SQL成绩":[76,88,95,82,80,93]
}
df = pd.DataFrame(data)

In [35]:
df[(df['性别']=='男') & (df['年龄']>18) & (df['Python成绩']>80)]

   姓名 性别  年龄  Python成绩  SQL成绩
1  李四  男  19        92     88

In [40]:
# 按行转
df.to_dict(orient='records')

[{'姓名': '张三', '性别': '男', '年龄': 18, 'Python成绩': 85, 'SQL成绩': 76},
 {'姓名': '李四', '性别': '男', '年龄': 19, 'Python成绩': 92, 'SQL成绩': 88},
 {'姓名': '王五', '性别': '女', '年龄': 18, 'Python成绩': 78, 'SQL成绩': 95},
 {'姓名': '赵六', '性别': '男', '年龄': 20, 'Python成绩': 65, 'SQL成绩': 82},
 {'姓名': '钱七', '性别': '女', '年龄': 19, 'Python成绩': 90, 'SQL成绩': 80},
 {'姓名': '孙八', '性别': '女', '年龄': 18, 'Python成绩': 88, 'SQL成绩': 93}]

In [39]:
# 按列转
df.to_dict(orient='list')

{'姓名': ['张三', '李四', '王五', '赵六', '钱七', '孙八'],
 '性别': ['男', '男', '女', '男', '女', '女'],
 '年龄': [18, 19, 18, 20, 19, 18],
 'Python成绩': [85, 92, 78, 65, 90, 88],
 'SQL成绩': [76, 88, 95, 82, 80, 93]}