In [52]:
import pandas as pd

In [53]:
s1 = pd.Series([1,2,3,4,5])
s2 = pd.Series([6,7,8,9,10])

pd.DataFrame({
    "第一列":s1,
    "第二列":s2,
})

   第一列  第二列
0    1    6
1    2    7
2    3    8
3    4    9
4    5   10

In [54]:
# 通过字典创建
df = pd.DataFrame({
    "name":['tom','tom','sse','srr','dd','re'],
    "age":[15,15,18,18,19,20],
    "score":[52.3,52.3,60.2,85,42.5,55]
},index=[1,2,3,4,5,6],columns=["name","score","age"])
df

  name  score  age
1  tom   52.3   15
2  tom   52.3   15
3  sse   60.2   18
4  srr   85.0   18
5   dd   42.5   19
6   re   55.0   20

In [55]:
# dataframe 的属性
print("行索引：")
print(df.index)
print("列标签：")
print(df.columns)
print("值")
print(df.values)

行索引：
Index([1, 2, 3, 4, 5, 6], dtype='int64')
列标签：
Index(['name', 'score', 'age'], dtype='object')
值
[['tom' 52.3 15]
 ['tom' 52.3 15]
 ['sse' 60.2 18]
 ['srr' 85.0 18]
 ['dd' 42.5 19]
 ['re' 55.0 20]]

In [56]:
print("维度：", df.ndim)
print("形状:",df.shape)
print("元素个数:",df.size)
print("数据类型：",df.dtypes)

维度： 2
形状: (6, 3)
元素个数: 18
数据类型： name      object
score    float64
age        int64
dtype: object

In [57]:
# 行列转置
print(df.T)
print(df.T.index)

          1     2     3     4     5     6
name    tom   tom   sse   srr    dd    re
score  52.3  52.3  60.2  85.0  42.5  55.0
age      15    15    18    18    19    20
Index(['name', 'score', 'age'], dtype='object')

In [58]:
df

  name  score  age
1  tom   52.3   15
2  tom   52.3   15
3  sse   60.2   18
4  srr   85.0   18
5   dd   42.5   19
6   re   55.0   20

In [59]:
# 获取元素
print(df.loc[4])    # 显式
print(df.iloc[3])   #隐式

name      srr
score    85.0
age        18
Name: 4, dtype: object
name      srr
score    85.0
age        18
Name: 4, dtype: object

In [60]:
# 某列
print(df.loc[:,'name'])
print(df.iloc[:,0])

1    tom
2    tom
3    sse
4    srr
5     dd
6     re
Name: name, dtype: object
1    tom
2    tom
3    sse
4    srr
5     dd
6     re
Name: name, dtype: object

In [61]:
# 单个元素
print(df.at[3,'score'])
print(df.iat[2,1])
print(df.loc[3,'score'])
print(df.iloc[2,1])

60.2
60.2
60.2
60.2

In [62]:
# 获取单列数据
print(df['name'])
print(type(df['name']))
print(df.name)
print(type(df.name))

1    tom
2    tom
3    sse
4    srr
5     dd
6     re
Name: name, dtype: object
<class 'pandas.core.series.Series'>
1    tom
2    tom
3    sse
4    srr
5     dd
6     re
Name: name, dtype: object
<class 'pandas.core.series.Series'>

In [63]:
print(df[['name']])
print(type(df[['name']]))
df[['name']]

  name
1  tom
2  tom
3  sse
4  srr
5   dd
6   re
<class 'pandas.core.frame.DataFrame'>

  name
1  tom
2  tom
3  sse
4  srr
5   dd
6   re

In [64]:
df[['name','score']]

  name  score
1  tom   52.3
2  tom   52.3
3  sse   60.2
4  srr   85.0
5   dd   42.5
6   re   55.0

In [65]:
# 查看部分数据
print(df.head(2))
print(df.tail(2))

  name  score  age
1  tom   52.3   15
2  tom   52.3   15
  name  score  age
5   dd   42.5   19
6   re   55.0   20

In [66]:
# 使用布尔索引筛选数据
df[df.score > 55]

  name  score  age
3  sse   60.2   18
4  srr   85.0   18

In [67]:
df[(df.score > 60) & (df.age < 40)]

  name  score  age
3  sse   60.2   18
4  srr   85.0   18

In [68]:
# 随机抽样
df.sample(3)

  name  score  age
2  tom   52.3   15
5   dd   42.5   19
1  tom   52.3   15

In [69]:
df

  name  score  age
1  tom   52.3   15
2  tom   52.3   15
3  sse   60.2   18
4  srr   85.0   18
5   dd   42.5   19
6   re   55.0   20

In [70]:
print(df.head())    # 默认五行
print(df.tail())

  name  score  age
1  tom   52.3   15
2  tom   52.3   15
3  sse   60.2   18
4  srr   85.0   18
5   dd   42.5   19
  name  score  age
2  tom   52.3   15
3  sse   60.2   18
4  srr   85.0   18
5   dd   42.5   19
6   re   55.0   20

In [71]:
# 查看元素是否包含在参数集合中
print(df.isin(['jack',20]))

    name  score    age
1  False  False  False
2  False  False  False
3  False  False  False
4  False  False  False
5  False  False  False
6  False  False   True

In [72]:
# 查看元素是否是缺失值
print(df.isna())

    name  score    age
1  False  False  False
2  False  False  False
3  False  False  False
4  False  False  False
5  False  False  False
6  False  False  False

In [73]:
print(df.sum())     # 一般不会这么使用

name     tomtomssesrrddre
score               347.3
age                   105
dtype: object

In [74]:
print(df['score'].sum())
print(df.score.max())
print(df.age.min())
print(df.score.mean())
print(df.score.median())
print(df.age.mode())

347.3
85.0
15
57.88333333333333
53.65
0    15
1    18
Name: age, dtype: int64

In [75]:
print(df.score.std())
print(df.score.var())
print(df.score.quantile(0.25))

14.477488272026564
209.59766666666673
52.3

In [76]:
print(df.describe())

           score        age
count   6.000000   6.000000
mean   57.883333  17.500000
std    14.477488   2.073644
min    42.500000  15.000000
25%    52.300000  15.750000
50%    53.650000  18.000000
75%    58.900000  18.750000
max    85.000000  20.000000

In [77]:
print(df.count())   # 每一列非缺失值的个数

name     6
score    6
age      6
dtype: int64

In [78]:
print(df.value_counts())

name  score  age
tom   52.3   15     2
dd    42.5   19     1
re    55.0   20     1
srr   85.0   18     1
sse   60.2   18     1
Name: count, dtype: int64

In [79]:
print(df.drop_duplicates())

  name  score  age
1  tom   52.3   15
3  sse   60.2   18
4  srr   85.0   18
5   dd   42.5   19
6   re   55.0   20

In [80]:
print(df.duplicated())

1    False
2     True
3    False
4    False
5    False
6    False
dtype: bool

In [81]:
# 随机抽样
df.sample(2)

  name  score  age
4  srr   85.0   18
6   re   55.0   20

In [82]:
print(df.score.replace(52.3,10))

1    10.0
2    10.0
3    60.2
4    85.0
5    42.5
6    55.0
Name: score, dtype: float64

In [83]:
df

  name  score  age
1  tom   52.3   15
2  tom   52.3   15
3  sse   60.2   18
4  srr   85.0   18
5   dd   42.5   19
6   re   55.0   20

In [84]:
df.cumsum()

               name  score  age
1               tom   52.3   15
2            tomtom  104.6   30
3         tomtomsse  164.8   48
4      tomtomssesrr  249.8   66
5    tomtomssesrrdd  292.3   85
6  tomtomssesrrddre  347.3  105

In [85]:
df.cummax()

  name  score  age
1  tom   52.3   15
2  tom   52.3   15
3  tom   60.2   18
4  tom   85.0   18
5  tom   85.0   19
6  tom   85.0   20

In [86]:
df.cummin(axis=0)

  name  score  age
1  tom   52.3   15
2  tom   52.3   15
3  sse   52.3   15
4  srr   52.3   15
5   dd   42.5   15
6   dd   42.5   15

In [87]:
print(df.sort_index(ascending=False))

  name  score  age
6   re   55.0   20
5   dd   42.5   19
4  srr   85.0   18
3  sse   60.2   18
2  tom   52.3   15
1  tom   52.3   15

In [90]:
print(df.sort_values(by=['score','age'],ascending=[True,False]))

  name  score  age
5   dd   42.5   19
1  tom   52.3   15
2  tom   52.3   15
6   re   55.0   20
3  sse   60.2   18
4  srr   85.0   18

In [91]:
df.nlargest(2,columns=['score','age'])

  name  score  age
4  srr   85.0   18
3  sse   60.2   18

In [92]:
df.nsmallest(2,columns=['score','age'])

  name  score  age
5   dd   42.5   19
1  tom   52.3   15